---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "edgecenter-dns-exporter.fullname" . }}
  labels:
    {{- include "edgecenter-dns-exporter.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.edgecenter }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
