version: "2.1"

services:

  edgecenter-dns_exporter:
    image: hroost/edgecenter-dns_exporter:latest
    container_name: edgecenter-dns_exporter
    ports:
      - "9886:9886"
    environment:
      - EDGECENTER_DNS_API_KEY=$(EDGECENTER_DNS_API_KEY)
    restart: always
